name: CI-Jo

on:≈
  push:
    branches:    # Array of patterns that match refs/heads
    - master  
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
#    - uses: iilness2/Github-Action@master
    - uses: ./github/action/workf
    - name: Run terraform version
      run: cd .. && terraform version
  go:
    runs-on: ubuntu-latest
    steps:
#    - name: try choose folder
#      uses: ./go/bin
    - name: Run go version
      run: cd .. && go version
