name: WOI

on:
  push:
    branches:
    - master
    paths:       # Push events containing matching files
    - github/*
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run terraform version
      run: ls -la && ./terra/terraform version
  go:
    runs-on: ubuntu-latest
    steps:
    - name: Run go version
      run: cd .. && go version
