name: push-action
on: [push]   
jobs:
 validate-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        if: github.actor == 'syukur91'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
     

