name: trigger

on: [pull_request]

jobs:

 validate-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check source files
      run: ls -al 
    - name: Check go version
      run: go version
    - name: Check terraform version
      run: terraform version
