name: trigger

on: [pull_request]

jobs:

 validate-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: HOOQTV/cloud-engineering@master
      # run: git clone "https://$GITHUB_TOKEN@github.com/myorg/other-private-repo.git" /other-private-repo
      env:
        GITHUB_TOKEN: 47f41e4d2701ec4304c5565cc13b8ce482e34276
    - name: Check source files
      run: ls -al 
    - name: Check go version
      run: go version
    - name: Check terraform version
      run: terraform version
