name: trigger

on: [pull_request]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Change Name
     run: echo did my first step run?
 terraform:
   runs-on: ubuntu-latest
   steps:
   - name: Using terraform
     uses: hashicorp/terraform-github-actions/plan@v0.3.5
   - name: Check terraform version
     run: terraform version

